const COLOR = require('./index')

const FONT_COLOR_CODE = {
  [COLOR.BLACK]: 30,
  [COLOR.RED]: 31,
  [COLOR.GREEN]: 32,
  [COLOR.YELLOW]: 33,
  [COLOR.BLUE]: 34,
  [COLOR.MAGENTA]: 35,
  [COLOR.CYAN]: 36,
  [COLOR.WHITE]: 37,
  [COLOR.BRIGHT_BLACK]: 90,
  [COLOR.BRIGHT_RED]: 91,
  [COLOR.BRIGHT_GREEN]: 92,
  [COLOR.BRIGHT_YELLOW]: 93,
  [COLOR.BRIGHT_BLUE]: 94,
  [COLOR.BRIGHT_MAGENTA]: 95,
  [COLOR.BRIGHT_CYAN]: 96,
  [COLOR.BRIGHT_WHITE]: 97
}

const BAKCGROUND_COLOR_CODE = {
  [COLOR.BLACK]: 40,
  [COLOR.RED]: 41,
  [COLOR.GREEN]: 42,
  [COLOR.YELLOW]: 43,
  [COLOR.BLUE]: 44,
  [COLOR.MAGENTA]: 45,
  [COLOR.CYAN]: 46,
  [COLOR.WHITE]: 47,
  [COLOR.BRIGHT_BLACK]: 100,
  [COLOR.BRIGHT_RED]: 101,
  [COLOR.BRIGHT_GREEN]: 102,
  [COLOR.BRIGHT_YELLOW]: 103,
  [COLOR.BRIGHT_BLUE]: 104,
  [COLOR.BRIGHT_MAGENTA]: 105,
  [COLOR.BRIGHT_CYAN]: 106,
  [COLOR.BRIGHT_WHITE]: 107
}

module.exports = {
  FONT_COLOR_CODE,
  BAKCGROUND_COLOR_CODE
}